/* Auto-generated by cbindgen — do not edit manually.
 *
 * E-Identity Stack FFI Bindings
 * Privacy-preserving anonymous identity registry for Logos Execution Zone.
 *
 * All JSON strings returned by ffi_* functions must be freed
 * with the corresponding ffi_*_free_string function.
 */

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct FfiChatJoiner FfiChatJoiner;

typedef struct FfiChatSession FfiChatSession;



#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Free a C-string allocated by this library.
 */
void ffi_chat_free_string(char *ptr);

/**
 * Create a new chat session as the room creator/admin.
 * Returns a pointer to FfiChatSession, or null on failure.
 */
struct FfiChatSession *ffi_chat_session_create_room(const char *room_id_ptr,
                                                    const uint8_t *commitment_ptr,
                                                    const char *username_ptr);

/**
 * Free a chat session.
 */
void ffi_chat_session_free(struct FfiChatSession *handle);

/**
 * Initialize Two-Tier SSS moderation with user's Nullifier Secret Key.
 * Returns JSON `{"ok":true}` or `{"error":"..."}`.
 */
char *ffi_chat_session_init_moderation(struct FfiChatSession *handle,
                                       const uint8_t *nsk_ptr,
                                       uint32_t k_strikes);

/**
 * Create a new joiner client to generate a KeyPackage and later process a Welcome message.
 */
struct FfiChatJoiner *ffi_chat_joiner_new(const uint8_t *commitment_ptr, const char *username_ptr);

/**
 * Get the hex-encoded KeyPackage for this joiner to share with the room admin.
 * Caller must free with `ffi_chat_free_string`.
 */
char *ffi_chat_joiner_get_key_package(struct FfiChatJoiner *handle);

/**
 * Complete the join process using the received Welcome message hex.
 * Consumes the joiner and returns a ready `*mut FfiChatSession`.
 */
struct FfiChatSession *ffi_chat_joiner_complete_join(struct FfiChatJoiner *handle,
                                                     const char *room_id_ptr,
                                                     const char *welcome_hex_ptr);

/**
 * Free a joiner client if join was aborted.
 */
void ffi_chat_joiner_free(struct FfiChatJoiner *handle);

/**
 * Add a new member to the room by their hex-encoded KeyPackage.
 * Advances the MLS epoch and returns JSON `{"ok":true, "welcome_hex":"..."}`.
 */
char *ffi_chat_session_add_member(struct FfiChatSession *handle, const char *key_package_hex_ptr);

/**
 * Send a protected room message.
 * Returns JSON `{"ok":true, "ciphertext_hex":"...", "tracing_tag":"...", "x_index":...}`.
 */
char *ffi_chat_session_send_protected_message(struct FfiChatSession *handle,
                                              const char *text_ptr,
                                              const uint8_t *post_salt_ptr,
                                              const uint8_t *mod_pubkeys_ptr,
                                              uint32_t mod_count,
                                              uint32_t threshold);

/**
 * Receive and decrypt a protected room message.
 * Returns JSON with plaintext, sender_commitment, tracing_tag, etc.
 */
char *ffi_chat_session_receive_protected_message(struct FfiChatSession *handle,
                                                 const char *ciphertext_hex_ptr);

/**
 * Send a 1-on-1 Direct Message encrypted with MLS ratchet tree.
 * Returns JSON `{"ok":true, "ciphertext_hex":"..."}`.
 */
char *ffi_chat_session_send_dm(struct FfiChatSession *handle, const char *text_ptr);

/**
 * Receive and decrypt a 1-on-1 Direct Message.
 * Returns JSON with plaintext, sender_commitment, and timestamp.
 */
char *ffi_chat_session_receive_dm(struct FfiChatSession *handle, const char *ciphertext_hex_ptr);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
