/* Auto-generated by cbindgen — do not edit manually.
 *
 * E-Identity Stack FFI Bindings
 * Privacy-preserving anonymous identity registry for Logos Execution Zone.
 *
 * All JSON strings returned by ffi_* functions must be freed
 * with the corresponding ffi_*_free_string function.
 */

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct FfiBlacklist FfiBlacklist;

typedef struct FfiModeratorRegistry FfiModeratorRegistry;

typedef struct FfiRegistrationClient FfiRegistrationClient;

typedef struct FfiReleaseShareValidator FfiReleaseShareValidator;

typedef struct FfiRoomRegistry FfiRoomRegistry;

typedef struct FfiUsernameRegistry FfiUsernameRegistry;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Free a JSON string returned by any `ffi_identity_*` function.
 */
void ffi_identity_free_string(char *ptr);

/**
 * Create a new RegistrationClient with a random NSK.
 */
struct FfiRegistrationClient *ffi_registration_new(void);

/**
 * Create a RegistrationClient from an existing 32-byte NSK.
 */
struct FfiRegistrationClient *ffi_registration_from_nsk(const uint8_t *nsk_ptr);

/**
 * Free a RegistrationClient handle.
 */
void ffi_registration_free(struct FfiRegistrationClient *ptr);

/**
 * Copy the 32-byte commitment into the provided output buffer.
 */
void ffi_registration_commitment(const struct FfiRegistrationClient *handle, uint8_t *out_ptr);

/**
 * Copy the 32-byte NSK into the provided output buffer.
 * WARNING: NSK is sensitive material — handle with care.
 */
void ffi_registration_nsk(const struct FfiRegistrationClient *handle, uint8_t *out_ptr);

/**
 * Prepare a registration payload. Returns JSON string.
 *
 * `node_pubkeys_ptr`: flat array of `node_count * 32` bytes.
 */
char *ffi_registration_prepare(const struct FfiRegistrationClient *handle,
                               const char *username,
                               const uint8_t *node_pubkeys_ptr,
                               uint32_t node_count,
                               uint32_t k_sss_threshold);

/**
 * Prepare a username change payload. Returns JSON string.
 */
char *ffi_registration_prepare_username_change(const struct FfiRegistrationClient *handle,
                                               const char *new_username);

struct FfiUsernameRegistry *ffi_username_registry_new(void);

void ffi_username_registry_free(struct FfiUsernameRegistry *ptr);

/**
 * Register a username for a commitment. Returns JSON `{"ok":true}` or `{"error":"..."}`.
 */
char *ffi_username_registry_register(struct FfiUsernameRegistry *handle,
                                     const uint8_t *commitment_ptr,
                                     const char *username);

/**
 * Lookup username by commitment. Returns JSON `{"username":"..."}` or `{"username":null}`.
 */
char *ffi_username_registry_lookup_by_commitment(const struct FfiUsernameRegistry *handle,
                                                 const uint8_t *commitment_ptr);

/**
 * Lookup commitment by username. Returns hex commitment or null.
 */
char *ffi_username_registry_lookup_by_username(const struct FfiUsernameRegistry *handle,
                                               const char *username);

struct FfiBlacklist *ffi_blacklist_new(void);

void ffi_blacklist_free(struct FfiBlacklist *ptr);

/**
 * Returns 1 if commitment is revoked, 0 if not, -1 on null pointer.
 */
int32_t ffi_blacklist_is_revoked(const struct FfiBlacklist *handle, const uint8_t *commitment_ptr);

/**
 * Add a commitment to the blacklist. Returns JSON result.
 */
char *ffi_blacklist_revoke(struct FfiBlacklist *handle, const uint8_t *commitment_ptr);

/**
 * Returns the number of revoked commitments, or -1 on null.
 */
int32_t ffi_blacklist_len(const struct FfiBlacklist *handle);

struct FfiRoomRegistry *ffi_room_registry_new(void);

void ffi_room_registry_free(struct FfiRoomRegistry *ptr);

/**
 * Create a room. Returns JSON with the created `RoomConfig` (including derived `room_id`).
 *
 * `mod_pubkeys_ptr`: flat array of `m_mod_total * 32` bytes.
 */
char *ffi_room_registry_create_room(struct FfiRoomRegistry *handle,
                                    const uint8_t *admin_commitment_ptr,
                                    uint32_t n_mod_threshold,
                                    uint32_t m_mod_total,
                                    const uint8_t *mod_pubkeys_ptr,
                                    uint64_t creation_index,
                                    uint32_t min_members_for_maturity);

/**
 * Join a room with signed consent. Returns JSON result.
 */
char *ffi_room_registry_join_room(struct FfiRoomRegistry *handle,
                                  const uint8_t *room_id_ptr,
                                  const uint8_t *member_commitment_ptr,
                                  const uint8_t *member_pubkey_ptr,
                                  const uint8_t *join_signature_ptr,
                                  uint64_t join_index);

/**
 * Sign a join consent message. Returns 64-byte signature as hex JSON.
 */
char *ffi_room_sign_join_consent(const uint8_t *room_id_ptr,
                                 const uint8_t *member_commitment_ptr,
                                 const uint8_t *nsk_ptr);

/**
 * Leave a room. Returns JSON result.
 */
char *ffi_room_registry_leave_room(struct FfiRoomRegistry *handle,
                                   const uint8_t *room_id_ptr,
                                   const uint8_t *member_commitment_ptr);

/**
 * Get active member count for a room.
 */
int32_t ffi_room_registry_active_member_count(const struct FfiRoomRegistry *handle,
                                              const uint8_t *room_id_ptr);

/**
 * Check if a commitment has active membership in a room. Returns 1/0/-1.
 */
int32_t ffi_room_registry_has_active_membership(const struct FfiRoomRegistry *handle,
                                                const uint8_t *room_id_ptr,
                                                const uint8_t *member_commitment_ptr);

struct FfiModeratorRegistry *ffi_moderator_registry_new(void);

void ffi_moderator_registry_free(struct FfiModeratorRegistry *ptr);

/**
 * Register moderators from a room config JSON string.
 */
char *ffi_moderator_registry_register_from_config(struct FfiModeratorRegistry *handle,
                                                  const char *room_config_json);

/**
 * Check if a pubkey is an active moderator for a room. Returns 1/0/-1.
 */
int32_t ffi_moderator_registry_is_moderator(const struct FfiModeratorRegistry *handle,
                                            const uint8_t *room_id_ptr,
                                            const uint8_t *pubkey_ptr);

/**
 * Get active moderator count for a room.
 */
int32_t ffi_moderator_registry_active_count(const struct FfiModeratorRegistry *handle,
                                            const uint8_t *room_id_ptr);

/**
 * Sign a strike as a moderator. Returns JSON `ModeratorSig`.
 */
char *ffi_strike_sign(const uint8_t *room_id_ptr,
                      const uint8_t *target_commitment_ptr,
                      const uint8_t *evidence_hash_ptr,
                      uint64_t strike_index,
                      const uint8_t *moderator_nsk_ptr);

/**
 * Validate a strike certificate against a moderator registry.
 * `certificate_json`: JSON-encoded `StrikeCertificate`.
 */
char *ffi_strike_validate(const char *certificate_json,
                          uint32_t n_mod_threshold,
                          const struct FfiModeratorRegistry *moderator_registry_handle);

/**
 * Create a ReleaseShareValidator with anti-Sybil config.
 */
struct FfiReleaseShareValidator *ffi_release_share_validator_new(uint32_t k_strikes,
                                                                 uint32_t k_rooms_min,
                                                                 uint64_t min_room_age_indexes,
                                                                 uint32_t min_room_members);

void ffi_release_share_validator_free(struct FfiReleaseShareValidator *ptr);

/**
 * Validate a ReleaseShare transaction.
 *
 * `release_share_json`: JSON-encoded `ReleaseShareTx`.
 * `used_strike_indexes_ptr`: flat array of `count * 32` bytes (previously used strike IDs).
 */
char *ffi_release_share_validate(const struct FfiReleaseShareValidator *handle,
                                 const char *release_share_json,
                                 const struct FfiRoomRegistry *room_registry_handle,
                                 const struct FfiModeratorRegistry *moderator_registry_handle,
                                 uint64_t current_index,
                                 const uint8_t *used_strike_indexes_ptr,
                                 uint32_t used_strike_count);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
