/* Auto-generated by cbindgen — do not edit manually.
 *
 * E-Identity Stack FFI Bindings
 * Privacy-preserving anonymous identity registry for Logos Execution Zone.
 *
 * All JSON strings returned by ffi_* functions must be freed
 * with the corresponding ffi_*_free_string function.
 */

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct FfiMemberClient FfiMemberClient;

typedef struct FfiModeratorClient FfiModeratorClient;

typedef struct FfiSlashAggregator FfiSlashAggregator;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

void ffi_free_string(char *ptr);

struct FfiMemberClient *ffi_member_new(const uint8_t *nsk_ptr, uint32_t k_strikes);

void ffi_member_free(struct FfiMemberClient *ptr);

/**
 * Prepare a post. Returns JSON string with PostPayload.
 */
char *ffi_member_prepare_post(struct FfiMemberClient *handle,
                              const uint8_t *message_ptr,
                              uint32_t message_len,
                              const uint8_t *post_salt_ptr,
                              const uint8_t *mod_pubkeys_ptr,
                              uint32_t mod_count,
                              uint32_t n_threshold);

struct FfiModeratorClient *ffi_moderator_new(const uint8_t *privkey_ptr);

void ffi_moderator_free(struct FfiModeratorClient *ptr);

void ffi_moderator_public_key(const struct FfiModeratorClient *handle, uint8_t *out_ptr);

char *ffi_moderator_issue_strike(const struct FfiModeratorClient *handle,
                                 const uint8_t *tracing_tag_ptr,
                                 const char *encrypted_share_json,
                                 uint32_t moderator_index);

struct FfiSlashAggregator *ffi_aggregator_new(uint32_t n_threshold,
                                              uint32_t k_strikes,
                                              const uint8_t *mod_pubkeys_ptr,
                                              uint32_t mod_count);

void ffi_aggregator_free(struct FfiSlashAggregator *ptr);

/**
 * Reconstruct a per-post strike from N certificates.
 */
char *ffi_aggregator_reconstruct_strike(const struct FfiSlashAggregator *handle,
                                        const uint8_t *tracing_tag_ptr,
                                        const char *certificates_json);

/**
 * Reconstruct the NSK from K accumulated strikes.
 */
char *ffi_aggregator_reconstruct_nsk(const struct FfiSlashAggregator *handle,
                                     const char *strikes_json);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
